<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rm_motors" params="parent prefix *origin">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="diameter" value="0.0667" />
  <xacro:property name="height1" value="0.01" /> <!-- base link -->
  <xacro:property name="height2" value="0.035" /> <!-- link 1 -->

  <joint name="${prefix}base_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="${prefix}base_link" />
  </joint>

  <!-- Base Link -->
  <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${diameter/2}" length="${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${diameter/2}" length="${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (diameter*diameter + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + diameter*diameter)}" iyz="0.0"
        izz="${mass / 12.0 * (diameter*diameter + diameter*diameter)}"/>
    </inertial>
  </link>

  <joint name="${prefix}joint1" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}link1"/>
    <origin xyz="0 0 ${height1}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="10.0"/>
  </joint>

  <!-- Middle Link -->
  <link name="${prefix}link1">
    <collision>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${diameter/2}" length="${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${diameter/2}" length="${height2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (diameter*diameter + height2*height2)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height2*height2 + diameter*diameter)}" iyz="0.0"
        izz="${mass / 12.0 * (diameter*diameter + diameter*diameter)}"/>
    </inertial>
  </link>


  <joint name="${prefix}marker_joint" type="fixed">
    <origin xyz="${0.3/2} 0 ${height2+0.01}" rpy="0 0 0" />
    <parent link="${prefix}link1"/>
    <child link="${prefix}marker_link" />
  </joint>

  <!-- to visualize motor position -->
  <link name="${prefix}marker_link">
  <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.02 0.02"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  </xacro:macro>

</robot>
